### PR TITLE
Sync fix and module change

### LINKED ISSUE #81: Sync XHR tiggers asynchronously
I found a bit of code using the following pattern:

```
var dataJSON;
makeSyncRequest(function (result) {
dataJSON = result;
});

var data = JSON.parse(dataJSON);
```

where makeSyncRequest performs a XHR async false with level 2 event listeners (load, error, timeout, abort).

The problem is that dataJSON is undefined when the xhook library is loaded globally. It looks like the reason why is here: https://github.com/jpillora/xhook/blame/f05d48cecb7176e7de23c3d5e8b7a1f28725a963/src/xhook.coffee#L288

Which causes the event listeners to all fire asynchronous to the execution. If a check was inserted so that emitFinal is performed synchronously in the async false case I think it will fix the issue.

### PR DESCRIPTION
**Pull request by rajsite**
Makes it so setTimeout for emitting the final events only occurs in the async use case.

Also changes the CommonJS case of the export to make it compatible with module bundlers (ie rollup) that expect the module object to be detected and used for exports.

Fixes #81 and #82

### CODE REVIEW

File: src/xhook.coffee [hunk 1]
```diff
@@ -591,5 +594,7 @@ XHookHttpRequest.DONE = 4;
 #publicise (amd+commonjs+window)
 if typeof define is "function" and define.amd
   define "xhook", [], -> xhook
+else if typeof module is "object" and module.exports
+  module.exports = xhook
 else
-  (@exports or @).xhook = xhook
+  WINDOW.xhook = xhook
```
Comment (morsdyce) [inline src/xhook.coffee]: WINDOW might be null in non browser environments such as react native and web workers, I've added a check if window exists before applying this fix.

**Comment by morsdyce** [comment]
Thanks for both of these fixes!
I'll release a new version in the next few minutes

File: src/xhook.coffee (hunk 1 above)
Comment (rajsite) [reply src/xhook.coffee]: 👍

**Comment by rajsite** [comment]
thanks for taking a look at them!
